### ISSUE TITLE
Motel 42 -> room 143 picture filetype is wrong 

### ISSUE THREAD

**Issue by gustavo-neiva** [luvotels/fs-hiring-test#9]
{"id"=>143,
 "name"=>"Twist and Shout Room",
 "picture"=>"https://luvotels-hiring-api.herokuapp.com/assets/tas-room.png"} picture not found, the image extension should be .jpg,  not .png

**Comment by jbfeldis** [comment]
Thanks @luizgzn I'll fix that asap!

**Comment by jbfeldis** [comment]
Fixed!
